package com.framework.v25.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;

import java.io.IOException;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.*;

@Service
@Slf4j
public class GitHubService {

    private final RestTemplate restTemplate;
    private final String       token;
    private final String       owner;
    private final String       defaultBranch;
    private final String       apiUrl;
    private final String       templateDir;

    @Autowired
    public GitHubService(
            RestTemplate restTemplate,
            @Value("${app.github.token}")            String token,
            @Value("${app.github.owner}")            String owner,
            @Value("${app.github.default-branch}")   String defaultBranch,
            @Value("${app.github.api-url}")          String apiUrl,
            @Value("${app.template.dir:/opt/eit-framework/templates}") String templateDir) {
        this.restTemplate = restTemplate;
        this.token        = token;
        this.owner        = owner;
        this.defaultBranch = defaultBranch;
        this.apiUrl       = apiUrl;
        this.templateDir  = templateDir;
    }

    // ── Result ────────────────────────────────────────────────

    public record GitHubResult(
            boolean success,
            String  repoUrl,
            String  cloneUrl,
            String  message
    ) {}

    // ── Main entry ────────────────────────────────────────────

    public GitHubResult setupProject(
            String repoName,
            String description,
            String inviteEmail) {

        String finalRepoName = repoName;

        try {
            // Step 1 — create repo
            String repoUrl = createRepo(finalRepoName, description);
            log.info("GitHub repo created: {}", repoUrl);

            // Step 2 — push Angular template files
            Path angularTemplate = Paths.get(templateDir, "angular");
            if (Files.exists(angularTemplate)) {
                pushDirectoryToGithub(finalRepoName, angularTemplate, "angular");
                log.info("Angular template pushed to {}/angular", finalRepoName);
            } else {
                log.warn("Angular template not found at {} — pushing placeholder", angularTemplate);
                pushFile(finalRepoName, "angular/README.md",
                        "# Angular Project\nGenerated by EIT Framework v2.5\n",
                        "Add Angular starter");
            }

            // Step 3 — push Spring Boot template files
            Path springTemplate = Paths.get(templateDir, "springboot");
            if (Files.exists(springTemplate)) {
                pushDirectoryToGithub(finalRepoName, springTemplate, "springboot");
                log.info("Spring Boot template pushed to {}/springboot", finalRepoName);
            } else {
                log.warn("Spring Boot template not found at {} — pushing placeholder", springTemplate);
                pushFile(finalRepoName, "springboot/README.md",
                        "# Spring Boot Project\nGenerated by EIT Framework v2.5\n",
                        "Add Spring Boot starter");
            }

            // Step 4 — push root README
            pushFile(finalRepoName, "README.md",
                    "# " + finalRepoName + "\n\nGenerated by EIT Framework v2.5\n\n" +
                    "## Structure\n- `angular/` — Angular 17 frontend\n- `springboot/` — Spring Boot 3.2 backend\n",
                    "Add root README");

            // Step 5 — send collaborator invitation
            sendInvitation(finalRepoName, inviteEmail);
            log.info("Invitation sent to {} for repo {}", inviteEmail, finalRepoName);

            return new GitHubResult(true, repoUrl,
                    "https://github.com/" + owner + "/" + finalRepoName + ".git",
                    "Repo created and invitation sent to " + inviteEmail);

        } catch (HttpClientErrorException e) {
            if (e.getStatusCode().value() == 422) {
                // Repo exists — retry once with suffix
                finalRepoName = repoName + "-" + (System.currentTimeMillis() % 10000);
                log.warn("Repo {} exists, retrying as {}", repoName, finalRepoName);
                return retrySetup(finalRepoName, description, inviteEmail);
            }
            log.error("GitHub setup failed for {}: {} — {}", repoName,
                    e.getStatusCode(), e.getResponseBodyAsString());
            return new GitHubResult(false, null, null,
                    "GitHub error: " + e.getStatusCode() + " — check token and owner in application.yml");
        } catch (Exception e) {
            log.error("GitHub setup failed for {}: {}", repoName, e.getMessage());
            return new GitHubResult(false, null, null, "GitHub setup failed: " + e.getMessage());
        }
    }

    private GitHubResult retrySetup(String repoName, String description, String inviteEmail) {
        try {
            String repoUrl = createRepo(repoName, description);
            Path angularTemplate  = Paths.get(templateDir, "angular");
            Path springTemplate   = Paths.get(templateDir, "springboot");
            if (Files.exists(angularTemplate))  pushDirectoryToGithub(repoName, angularTemplate, "angular");
            else pushFile(repoName, "angular/README.md", "# Angular Project\n", "Add Angular starter");
            if (Files.exists(springTemplate))   pushDirectoryToGithub(repoName, springTemplate, "springboot");
            else pushFile(repoName, "springboot/README.md", "# Spring Boot Project\n", "Add Spring Boot starter");
            pushFile(repoName, "README.md",
                    "# " + repoName + "\n\nGenerated by EIT Framework v2.5\n", "Add README");
            sendInvitation(repoName, inviteEmail);
            return new GitHubResult(true, "https://github.com/" + owner + "/" + repoName,
                    "https://github.com/" + owner + "/" + repoName + ".git",
                    "Repo created as " + repoName + ", invitation sent to " + inviteEmail);
        } catch (Exception ex) {
            log.error("Retry also failed for {}: {}", repoName, ex.getMessage());
            return new GitHubResult(false, null, null, "GitHub retry failed: " + ex.getMessage());
        }
    }

    // ── Push entire directory recursively to GitHub ───────────

    private void pushDirectoryToGithub(String repoName, Path dir, String prefix) throws IOException {
        Files.walkFileTree(dir, new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                // Skip hidden files, node_modules, .git, target, dist
                String relative = dir.relativize(file).toString().replace("\\", "/");
                if (shouldSkip(relative)) return FileVisitResult.CONTINUE;

                String repoPath = prefix + "/" + relative;
                byte[] content  = Files.readAllBytes(file);

                try {
                    pushFileBytes(repoName, repoPath, content,
                            "Add " + repoPath);
                } catch (Exception e) {
                    log.warn("Skipping {}: {}", repoPath, e.getMessage());
                }
                return FileVisitResult.CONTINUE;
            }
        });
    }

    private boolean shouldSkip(String path) {
        return path.startsWith("node_modules/")
                || path.startsWith(".git/")
                || path.startsWith("target/")
                || path.startsWith("dist/")
                || path.startsWith(".angular/")
                || path.startsWith("build/")
                || path.contains("/.git/")
                || path.endsWith(".class")
                || path.endsWith(".jar");
    }

    // ── Create repo ───────────────────────────────────────────

    private String createRepo(String repoName, String description) {
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("name",        repoName);
        body.put("description", description != null ? description : "EIT Framework v2.5 project");
        body.put("private",     false);
        body.put("auto_init",   false);

        try {
            ResponseEntity<Map> res = restTemplate.exchange(
                    apiUrl + "/user/repos", HttpMethod.POST,
                    new HttpEntity<>(body, githubHeaders()), Map.class);
            Map resBody = res.getBody();
            if (resBody == null) throw new RuntimeException("Empty response from GitHub");
            return (String) resBody.get("html_url");
        } catch (HttpClientErrorException e) {
            log.error("createRepo failed — {}: {}", e.getStatusCode(), e.getResponseBodyAsString());
            throw e;
        }
    }

    // ── Push text file ────────────────────────────────────────

    private void pushFile(String repoName, String path, String content, String message) {
        pushFileBytes(repoName, path, content.getBytes(), message);
    }

    // ── Push binary/text file bytes ───────────────────────────

    private void pushFileBytes(String repoName, String path, byte[] content, String message) {
        String url     = apiUrl + "/repos/" + owner + "/" + repoName + "/contents/" + path;
        String encoded = Base64.getEncoder().encodeToString(content);

        Map<String, Object> body = new LinkedHashMap<>();
        body.put("message", message);
        body.put("content", encoded);
        body.put("branch",  defaultBranch);

        try {
            restTemplate.exchange(url, HttpMethod.PUT,
                    new HttpEntity<>(body, githubHeaders()), Map.class);
        } catch (HttpClientErrorException e) {
            if (e.getStatusCode().value() == 422) {
                log.debug("File {} already exists — skipping", path);
                return;
            }
            throw e;
        }
    }

    // ── Send invitation ───────────────────────────────────────

    private void sendInvitation(String repoName, String usernameOrEmail) {
        String url = apiUrl + "/repos/" + owner + "/" + repoName
                + "/collaborators/" + usernameOrEmail;
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("permission", "push");
        try {
            restTemplate.exchange(url, HttpMethod.PUT,
                    new HttpEntity<>(body, githubHeaders()), Map.class);
        } catch (HttpClientErrorException e) {
            log.warn("Invitation to {} failed: {} — user may need to be added manually",
                    usernameOrEmail, e.getStatusCode());
        }
    }

    // ── Invitation status ─────────────────────────────────────

    public String getInvitationStatus(String repoName, String username) {
        try {
            String url = apiUrl + "/repos/" + owner + "/" + repoName + "/invitations";
            ResponseEntity<List> res = restTemplate.exchange(
                    url, HttpMethod.GET, new HttpEntity<>(githubHeaders()), List.class);
            List<Map> invites = res.getBody();
            if (invites != null) {
                for (Map inv : invites) {
                    Map invitee = (Map) inv.get("invitee");
                    if (invitee != null && username.equalsIgnoreCase((String) invitee.get("login")))
                        return "PENDING";
                }
            }
            return checkCollaborator(repoName, username) ? "ACCEPTED" : "NOT_FOUND";
        } catch (Exception e) {
            return "UNKNOWN";
        }
    }

    private boolean checkCollaborator(String repoName, String username) {
        try {
            restTemplate.exchange(
                    apiUrl + "/repos/" + owner + "/" + repoName + "/collaborators/" + username,
                    HttpMethod.GET, new HttpEntity<>(githubHeaders()), Map.class);
            return true;
        } catch (HttpClientErrorException e) {
            return false;
        }
    }

    public boolean resendInvitation(String repoName, String username) {
        try { sendInvitation(repoName, username); return true; }
        catch (Exception e) { return false; }
    }

    public void deleteRepo(String repoName) {
        try {
            restTemplate.exchange(apiUrl + "/repos/" + owner + "/" + repoName,
                    HttpMethod.DELETE, new HttpEntity<>(githubHeaders()), Void.class);
            log.info("GitHub repo deleted: {}", repoName);
        } catch (Exception e) {
            log.warn("Failed to delete repo {}: {}", repoName, e.getMessage());
        }
    }

    // ── Headers ───────────────────────────────────────────────

    private HttpHeaders githubHeaders() {
        HttpHeaders h = new HttpHeaders();
        h.setContentType(MediaType.APPLICATION_JSON);
        h.set("Accept",        "application/vnd.github+json");
        h.set("Authorization", "token " + token);
        h.set("X-GitHub-Api-Version", "2022-11-28");
        return h;
    }
}